version: '3.8'
services:
  mongodb:
    image: mongo:6.0.3
    container_name: mongodb_container
    volumes:
      - ./db/mongodb/data:/data/db
    ports:
      - "27017:27017"
    networks:
      - flowday
    command: mongod --noauth

networks:
  flowday:
